language: php

matrix:
  include:
  - php: 5.3
  
  fast_finish: true

  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

install : scripts/http-auth.sh

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist

deploy:
    provider: script
    script: scripts/deploy.sh
    skip_cleanup: false
    on:
      tags: true
      condition: "$TRAVIS_PHP_VERSION = 5.6"

notifications:
    slack: crazyfactory:Z3NJKlj5jdPOE1YrjPPyDPKb
